# Generated by Django 3.2.5 on 2021-07-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_auto_20210705_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
