# Generated by Django 3.2.5 on 2021-07-05 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True, verbose_name='Unique id'),
        ),
    ]
