# Generated by Django 3.2.5 on 2021-07-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0014_auto_20210713_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test-product-01'),
            preserve_default=False,
        ),
    ]
