# Generated by Django 3.2.5 on 2021-07-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0022_auto_20210714_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
