# Generated by Django 3.2.5 on 2021-07-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0030_alter_billingaddress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(default='Vilnius ', max_length=100),
            preserve_default=False,
        ),
    ]
